# Generated by Django 5.2.5 on 2025-09-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_category_project_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.task'),
        ),
    ]
