# Generated by Django 5.2.5 on 2025-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_gigs',
            field=models.IntegerField(default=0),
        ),
    ]
