# Generated by Django 5.2.5 on 2025-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_completed_gigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_type',
            field=models.CharField(choices=[('upload', 'Uploaded'), ('avatar', 'Avatar'), ('google', 'Google')], default='avatar', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_avatar',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
