# Generated by Django 5.2.5 on 2025-09-04 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_avatar_type_userprofile_google_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations', to='api.project'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='group_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('project', 'Project Restricted')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_project', to='api.conversation'),
        ),
    ]
