# Generated by Django 5.2.5 on 2025-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_address_userprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, help_text='Main course content file (ZIP, PDF, etc.)', null=True, upload_to='course_files/'),
        ),
    ]
