# Generated by Django 5.2.5 on 2025-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_course_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
