# Generated by Django 5.2.5 on 2025-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
    ]
