# Generated by Django 5.2.5 on 2025-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_delivery_time_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
