# Generated by Django 5.2.5 on 2025-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gig_dislikes_count_gig_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('message', 'New Message'), ('job', 'Job Alert'), ('proposal', 'Proposal Update'), ('payment', 'Payment Update'), ('system', 'System Notification'), ('review', 'Review Notification'), ('help', 'Help Request'), ('group_invite', 'Group Invitation')], max_length=15),
        ),
    ]
