# Generated by Django 5.2.5 on 2025-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_populate_newsletter_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=10),
        ),
    ]
