# Generated by Django 5.2.5 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='new_assessments', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='gig',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='gigs', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='api.subcategory'),
        ),
    ]
