# Generated by Django 5.2.5 on 2025-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_assessment_subcategories_course_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingresponse',
            name='interested_subcategories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='api.subcategory'),
        ),
    ]
