# Generated by Django 5.2.5 on 2025-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_enhanced_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_session_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
