# Generated by Django 5.2.5 on 2025-09-16 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_profile_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_level', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('expert', 'Expert')], default='basic', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_badge',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='verification/documents/')),
                ('id_document_type', models.CharField(blank=True, choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('certificate', 'Professional Certificate'), ('portfolio', 'Portfolio Link')], max_length=20, null=True)),
                ('secondary_document', models.FileField(blank=True, null=True, upload_to='verification/documents/')),
                ('secondary_document_type', models.CharField(blank=True, choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('certificate', 'Professional Certificate'), ('portfolio', 'Portfolio Link')], max_length=20, null=True)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='verification/certificates/')),
                ('portfolio_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=500, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
