# Generated by Django 5.2.5 on 2025-09-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_verification_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('message', 'New Message'), ('job', 'Job Alert'), ('proposal', 'Proposal Update'), ('payment', 'Payment Update'), ('system', 'System Notification'), ('review', 'Review Notification'), ('help', 'Help Request'), ('group_invite', 'Group Invitation'), ('verification', 'Verification Update')], max_length=15),
        ),
    ]
