# Generated by Django 5.2.5 on 2025-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_report_models'),
        ('api', '0034_add_verification_notification_type'),
    ]

    operations = [
    ]
