# Generated by Django 5.2.5 on 2025-09-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_fix_report_models_conflict'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='api_report_status_2ddde8_idx',
            old_name='api_report_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='api_report_reporte_efedd4_idx',
            old_name='api_report_reported_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='api_report_report__6f44c4_idx',
            old_name='api_report_type_category_idx',
        ),
        migrations.AddField(
            model_name='assessment',
            name='category_name',
            field=models.CharField(blank=True, help_text='Category name for quick access', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subcategory_names',
            field=models.TextField(blank=True, help_text='Comma-separated subcategory names for quick access'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_name',
            field=models.CharField(blank=True, help_text='Category name for quick access', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory_names',
            field=models.TextField(blank=True, help_text='Comma-separated subcategory names for quick access'),
        ),
        migrations.AddField(
            model_name='gig',
            name='category_name',
            field=models.CharField(blank=True, help_text='Category name for quick access', max_length=100),
        ),
        migrations.AddField(
            model_name='gig',
            name='subcategory_names',
            field=models.TextField(blank=True, help_text='Comma-separated subcategory names for quick access'),
        ),
        migrations.AddField(
            model_name='job',
            name='category_name',
            field=models.CharField(blank=True, help_text='Category name for quick access', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='subcategory_names',
            field=models.TextField(blank=True, help_text='Comma-separated subcategory names for quick access'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='api.category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_names',
            field=models.TextField(blank=True, help_text='Comma-separated category names'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_freelancers', to='api.category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_category_name',
            field=models.CharField(blank=True, help_text='Primary category name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subcategory_names',
            field=models.TextField(blank=True, help_text='Comma-separated subcategory names'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('order_updates', 'Order Updates'), ('messages', 'Messages'), ('job_alerts', 'Job Alerts'), ('system_notifications', 'System Notifications'), ('marketing', 'Marketing Communications'), ('proposals', 'Proposal Updates'), ('payments', 'Payment Notifications'), ('reviews', 'Review Notifications'), ('verification', 'Verification Updates')], max_length=20),
        ),
    ]
