# Generated by Django 5.2.5 on 2025-09-17 01:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_supportticket_ticketreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('message', 'New Message'), ('job', 'Job Alert'), ('proposal', 'Proposal Update'), ('payment', 'Payment Update'), ('system', 'System Notification'), ('review', 'Review Notification'), ('help', 'Help Request'), ('group_invite', 'Group Invitation'), ('verification', 'Verification Update'), ('support', 'Support Ticket')], max_length=15),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_signups', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('withdrawn_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('signup_bonus_paid', models.BooleanField(default=False)),
                ('signup_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.referralcode')),
            ],
            options={
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(choices=[('signup_bonus', 'Signup Bonus'), ('earnings_percentage', 'Earnings Percentage'), ('bonus', 'Special Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source_transaction_id', models.IntegerField(blank=True, null=True)),
                ('source_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='api.referral')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_referral_earnings', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable entire referral system')),
                ('signup_bonus_enabled', models.BooleanField(default=True, help_text='Enable signup bonus for referrals')),
                ('earnings_percentage_enabled', models.BooleanField(default=False, help_text='Enable percentage from referred user earnings')),
                ('signup_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Amount referrer earns when someone signs up with their link', max_digits=10)),
                ('earnings_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text="Percentage of referred user's earnings that referrer gets", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('max_referrals_per_user', models.IntegerField(default=100, help_text='Maximum referrals per user (0 = unlimited)')),
                ('min_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum amount before referral earnings can be withdrawn', max_digits=10)),
                ('earnings_duration_days', models.IntegerField(default=365, help_text='How many days referrer earns from referred user (0 = forever)')),
                ('require_email_verification', models.BooleanField(default=True, help_text='Referred user must verify email')),
                ('require_first_purchase', models.BooleanField(default=False, help_text='Referred user must make first purchase')),
                ('min_account_age_hours', models.IntegerField(default=24, help_text='Minimum account age before earning referral bonus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('balance', 'Add to Account Balance')], default='balance', max_length=20)),
                ('account_details', models.JSONField(default=dict, help_text='Payment account details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_referral_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
